# Generated by Django 3.1.14 on 2024-11-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_muallif',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
